name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: AerotechXD
          token: ${{ secrets.GITHUB_TOKEN }}
          template: classic
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: javascript,html,css
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_lines: yes
